[SUPABASE]
SUPABASE_URL = "https://cslcllqnwtemrsqirath.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzbGNsbHFud3RlbXJzcWlyYXRoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwMjAwNzQsImV4cCI6MjA1MDU5NjA3NH0.aWzKv3vXw5ROnWGl-8i1nOo42CtDKYiqBqbum-iXw3Q"
